# Generated by Django 4.1.2 on 2023-03-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_alter_usuario_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('apellido', models.CharField(max_length=40, null=True)),
                ('genero', models.CharField(choices=[(0, 'Seleccione su genero'), (1, 'Masculino'), (2, 'Femenino'), (3, 'Otros')], default=0, max_length=40, null=True)),
            ],
        ),
    ]
